# Generated by Django 5.0.3 on 2024-03-06 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_curso_entregable_profesor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entregable',
        ),
    ]
